version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0   # change to 6.0 or 7.0 if needed

  build:
    commands:
      - echo "Listing files"
      - ls -la
      - echo "Restoring NuGet packages"
      - dotnet restore
      - echo "Building Web API"
      - dotnet build --configuration Release
      - echo "Publishing Web API"
      - dotnet publish -c Release -o output

artifacts:
  files:
    - '**/*'
