version: 0.2

phases:
  install:
    commands:
      # CodeBuild minimal images may not set HOME, .NET 8 requires it
      - echo "Setting HOME for .NET CLI"
      - export HOME=/root
      - export DOTNET_CLI_HOME=/root
      - dotnet --info

  build:
    commands:
      - echo "Listing files"
      - ls -la

      - echo "Clearing NuGet cache"
      - dotnet nuget locals all --clear

      - echo "Restoring NuGet packages"
      - dotnet restore AWSWebApplication.sln

      - echo "Building Web API"
      - dotnet build AWSWebApplication.sln --configuration Release --no-restore

      - echo "Publishing Web API"
      - dotnet publish AWSWebApplication.csproj -c Release -o output --no-build

artifacts:
  files:
    - output/**/*

